### ISSUE TITLE
IRQ request failed -4

### ISSUE THREAD

**Issue by jklmnn** [sigboe/gslX68X#2]
I have tried your driver with a surftab wintron 7.0 tablet from TrekStor. I have used the firmware file mentioned in [this](https://github.com/Manouchehri/vi8/issues/1) thread which is directly from TrekStore: http://download.trekstor.de/tl_files/userFiles/products/surftab_wintron_70_v2/PG-HK70DR2503.zip
This is exactly the device I have.
I got the following messages on insmod:

```
  silead_ts i2c-MSSL1680:00: firmware: direct-loading firmware mssl1680.fw
  input: silead_ts as /devices/platform/80860F41:03/i2c-3/i2c-MSSL1680:00/input/input4
  silead_ts i2c-MSSL1680:00: IRQ request failed -4
  silead_ts: probe of i2c-MSSL1680:00 failed with error -4
```

EDIT: I tried it again and it brought an initialization error because it hung more than 120 seconds.
I'm getting the following message `silead_ts i2c-MSSL1680:00 Initialization error, status 0x0`.

**Comment by barni2000** [comment]
Are you extracted the firmware or just rename?

**Comment by jklmnn** [comment]
I just renamed the `SileadTouch.fw` file. I thought that this is the right firmware file.

**Comment by barni2000** [comment]
You should extracted from SileadTouch.fw with [onitake/gslx680-acpi](https://github.com/onitake/gslx680-acpi) with these tools.

**Comment by jklmnn** [comment]
Thanks, I have extracted the firmware, now I'm getting:

```
i2c_dw_handle_tx_abort: lost arbitration
Firmware load error -11
```

**Comment by barni2000** [comment]
There are a working method for this tablet. [https://github.com/Manouchehri/vi8/issues/1](https://github.com/Manouchehri/vi8/issues/1)
Please read the thread end.

**Comment by jklmnn** [comment]
I have read this thread (this is how I found you), but I don't have a `/sys/class/gpio`.
I only can find the device in `/sys/bus/i2c/devices`, but I also don't have `/dev/i2c`.
EDIT: I also tried /onitake/gslx680-acpi s module, but that gives me: `gsl_ts_probe: error obtaining power pin GPIO ressource`.

**Comment by barni2000** [comment]
At the thread end there is a firmware for your tablet, you should try that with gslx680-acpi.

**Comment by jklmnn** [comment]
Thanks, i didn't found it before (I looked for something older in the mid of the thread, there were also several firmwares and I didn't expect it to get active again). I will look their for further help.
Thanks for your effort!
