### ISSUE TITLE
You will need to place a firmware file at /lib/firmware/[hid].fw where you replace [hid] with the HID ID of your device.

### ISSUE THREAD

**Issue by youling257** [sigboe/gslX68X#3]
what mean ? what hid.fw ?  what “ [hid] with the HID ID of your device” ?

**Comment by onitake** [comment]
The HID is the Hardware ID, i.e. the name of the device in the ACPI DSDT or the DeviceTree entry.
It's a very confusing term. Maybe there should be some clarification in the README.

The ACPI HID is `MSSL1680` in all cases I've seen so far, but it could be different. Try it, and check the kernel log if it doesn't work.

**Comment by onitake** [comment]
Sorry, it should be `mssl1680`. The HID is capitalised, but the driver lowercases it.

**Comment by youling257** [comment]
can't  understand
silead.ko need what fw ?

**Comment by onitake** [comment]
If you extract firmware from the Android driver using [fw_extractor](https://github.com/onitake/gsl-firmware/blob/master/tools/fw_extractor), you just need to rename the file to mssl1680.fw and copy to /lib/firmware.

If you have SileadTouch.fw from the Windows driver instead, use [unscramble SileadTouch.fw mssl1680.fw](https://github.com/onitake/gsl-firmware/blob/master/tools/unscramble), then copy mssl1680.fw to /lib/firmware.
